INSERT INTO tb_role(authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role(authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('ana', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação e aventura');
INSERT INTO tb_genre (name) VALUES ('Drama');
INSERT INTO tb_genre (name) VALUES ('Comédia romântica');
INSERT INTO tb_genre (name) VALUES ('Ficção científica');
INSERT INTO tb_genre (name) VALUES ('Terror');

INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Os Novos Mutantes', null, 2020,'https://static.wikia.nocookie.net/disney/images/5/55/Os_Novos_Mutantes_-_P%C3%B4ster_Nacional.jpg/revision/latest?cb=20211212000521&path-prefix=pt-br', 'Cinco jovens mutantes descobrem o alcance de seus poderes e lidam com traumas do passado. Eles são mantidos em uma instituição secreta pela Dra. Cecilia Reyes, que promete controlar suas habilidades. Porém, eles descobrem que nada é o que parece.',1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Thor: Amor e Trovão', null, 2022, 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/08/Thor_Love_and_Thunder_poster.jpg/250px-Thor_Love_and_Thunder_poster.jpg', '“Thor: Amor e Trovão”, da Marvel Studios, encontra o Deus do Trovão numa jornada diferente de tudo o que já enfrentou – a procura pela paz interior. Mas a reforma de Thor é interrompida por um assassino galáctico conhecido como Gorr, o Carniceiro dos Deuses, que procura a extinção dos deuses. Para combater a ameaça, Thor pede a ajuda da Rei Valkiria, de Korg e da ex-namorada Jane Foster, que – para surpresa de Thor – empunha inexplicavelmente o seu martelo mágico, Mjolnir, e se intitula a Poderosa Thor. Juntos, eles embarcam numa angustiante aventura cósmica para descobrir o mistério da vingança do Carniceiro dos Deuses e detê-lo antes que seja tarde demais.',1);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Sem Saída', null, 2022, 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/star/3FBD404B263BD961469A6DA2EF005EF9F110FB902F25FBA4346FC17FA3B584B6/scale?width=1200&aspectRatio=1.78&format=jpeg', 'No Exit é um filme de suspense americano dirigido por Damien Power a partir de um roteiro de Andrew Barrer e Gabriel Ferrari, baseado no romance de 2017 de mesmo nome de Taylor Adams.',2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Coringa', null, 2019, 'https://capricho.abril.com.br/wp-content/uploads/2019/10/coringa-joker-1.jpg?quality=85&strip=info&w=1024&resize=1200,800', 'Isolado, intimidado e desconsiderado pela sociedade, o fracassado comediante Arthur Fleck inicia seu caminho como uma mente criminosa após assassinar três homens em pleno metrô. Sua ação inicia um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.',2);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Cidade Perdida', null, 2022, 'https://br.web.img3.acsta.net/pictures/22/02/10/15/10/4068810.jpg', 'A brilhante e reclusa autora Loretta Sage escreve romances populares de aventura, cujas capas são estreladas pelo belo modelo Alan. Durante a turnê de promoção de seu novo livro, Loretta é raptada.', 3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Casal de Fachada', null, 2022,'https://prod-ripcut-delivery.disney-plus.net/v1/variant/star/7AF3FBF433191D99C6E6389380E8D83861F403C828E244D6D948AFA36174F755/scale?width=1200&aspectRatio=1.78&format=jpeg', 'A atriz Olivia enfrenta um desastre quando um paparazzi tira uma foto dela com seu amante Vincent. O manobrista Antonio acidentalmente aparece na mesma foto, e é alistado para posar como o novo namorado de Olivia para encobrir o caso.',3);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Homem-Aranha: Sem Volta para Casa', null, 2021, 'https://www.sonypictures.com.br/sites/brazil/files/2022-03/KEY%20ART_SPIDER%20NO%20WAY%20HOME.JPG', 'O Homem-Aranha precisa lidar com as consequências da sua verdadeira identidade ter sido descoberta.',4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Projeto Adam', null, 2022, 'https://static.wikia.nocookie.net/dublagem/images/7/75/O-Projeto-Adam-filme-Netflix.jpg/revision/latest?cb=20220320173254&path-prefix=pt-br', 'Um viajante do tempo volta ao ano de 2022 por acidente e acaba se encontrando com seu eu mais novo. Juntos, e sendo caçados por forças do futuro, os dois embarcam em uma missão para consertar a linha temporal e salvar seus entes queridos.',4);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('O Telefone Preto', null, 2021,' https://br.web.img3.acsta.net/pictures/22/06/23/21/10/1998178.jpg', 'Finney Shaw, de 13 anos, é sequestrado por um sádico assassino mascarado e mantido em um porão à prova de som. Até que um telefone desconectado na parede começa a tocar, e ele logo descobre que pode ouvir as vozes das vítimas anteriores do maníaco.',5);
INSERT INTO tb_movie (title, sub_Title, year, img_Url, synopsis, genre_id) VALUES ('Rogai por Nós', null, 2021, 'https://br.web.img3.acsta.net/pictures/21/03/17/13/18/1808324.jpg', 'Jornalista investiga uma jovem com deficiência auditiva que foi visitada pela Virgem Maria e, repentinamente, passa a ouvir, falar e curar os enfermos.',5);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Adorei a Marvel ter inovado trazendo uma proposta mais puxada para o gênero suspense! Fugiu do lugar comum desses filmes de super herói da Marvel - receita tradicional e, na minha opinião, bem cansativa e previsível - e talvez por isso não é aquele típico filme de massa, que agrada todo mundo - ainda assim, seu estilo diferentão, para mim, é seu grande trunfo. Os atores e atrizes estão excelentes e muito identificáveis. História boa. Pena que não haverá continuação. Amei!', 1, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('O filme não sebe aproveitar seus personagens então , transforma eles em "comediantes de stand up " que pra mim é um completo absurdo, esse filme não consegue tratar nada com seriedade nem quando o Gorr invade Asgard e leva as crianças eu também não entendi o porque ele levou as crianças mas... Aí sem mais nem menos aparece o filho do Heimdall com uma CABEÇA FLUTUANTE RIDÍCULA CONVERSANDO COM O THOR  , e mais esse filho do Heimdall   nem cê quer foi citado nos outros filmes, surgiu do nada , não faz o menor sentido , como muita coisa nesse filme. O vilã do filme além de não ser nada fiel aos quadrinhos tanto na sua aparência quanto em suas ações , ele também não faz jus ao seu nome  carniceiro dos deuses  tudo o que eu vi foi ele matando um só deus no início do filme , nos quadrinhos o Gorr escraviza os deuses cria uma bomba com capacidade de matar todos os deuses de uma só vez , só aí já dá pra perceber a diferença entre o Gorr das HQS pro Gorr do filme a gente vê o quanto esse Gorr do filme é fraco  , ele era pra ser o melhor vilão do Thor .O Thor não passava de um comediante sem graça , estava ridículo no filme , a  luta dele com o Gorr não chega nem perto do que  poderia ser , deveria ser épico mas infelizmente não foi . Eles colocaram CRIANÇAS PARA LUTAR CONTRA MONSTROS , não tem condições PARECIA QUE EU ESTAVA ASSISTINDO" A CRECHE DO PAPAI " OU "UM TIRA NO JARDIM DE INFÂNCIA" O Thor nas HQS foi alimentado por todos os deuses através do espaço e do tempo, para parar a Bomba Divina. Ele se tornou o Deus dos Deuses, dominou a escuridão da Necroespada em seu próprio corpo e usou o seu Mjolnir e o Mjolnir do Rei Thor, um em cada mão, para derrotar Gorr. "Resumindo, esse filme foi vergonhoso e ridículo , era pra ser um dos melhores mas é o pior filme sem dúvida .', 2, 2);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Indescritivelmente bom. Filme incrível. O suspense, a agonia e o desespero que o filme passa são intensos. Quando eu procuro por filme de suspense eu espero ver o protagonista lutando pela vida, brigando com um maníaco, e é exatamente o que esse filme mostra.', 1, 3);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Esse foi um dos melhores filmes que eu já vi, com certeza! Ele foi capaz de me prender, de me fazer criar uma empatia e de me indentificar com o personagem de uma forma tremenda, o drama é muito envolvente e a atuação de Joaquin Phoenix é fantástica, tanto é que ganhou o merecidíssimo Oscar, e ele realmente mergulha no personagem e é isso, simplesmente os momentos mostrados no filme são uma jornada dentro de uma psique que simplesmente é julgada como insana e rasa, deu um novo ar para a personagem, total. A música tocada do Sinatra, "That''s life", dá um match com o coringa mostrado e acaba passando uma vibe tão boa, principalmente na cena da escada. O visual é outra coisa que chama atenção, a atmosfera dark é muito imersiva. Enfim, não me julguem, mas ver esse filme foi como fazer terapia para mim.', 2, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Acabei de assistir, é um filme mt bem elaborado. A Sandra sempre ganhando as telas e mostrando que faz o melhor: Atuar. A história do filme é bem elaborada, te prende do início ao fim. Os demais atores também executam bem o roteiro. Gostei e recomendo demais!', 1, 5);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filmes de clichê romântico são como o tiro certeiro da indústria, por pior que seja sempre tem um público consumindo. E todo streaming já notou isso, e aproveitando o hype dos filmes de romance nesse mês dos namorados, o Star Plus lança o filme “Casal de Fachada” (The Valet). Um filme esquecível, que nem no tédio vale a pena.', 2, 6);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('(COM SPOILERS!!!) Simplesmente a melhor produção cinematográfica já feita, de qualquer gênero... não preciso dizer que é o melhor filme de super herói de todos os tempos então né... para os verdadeiros fãs dos quadrinhos, isso foi um presentaço pra vida toda, TUDO nesse filme ta perfeito, o roteiro, como se desenrlou pra chegar no apse do fime, os vilões, as conversas, as atuações e tudo mais que você imaginar, a participação do Tobey Maguire e do Andrew Garfield (ARANHAS DE OUTRO UNIVERSO) foi a cereja do bolo pra mim, carismaticos, engraçados e etc... eu diria que o Andrew foi o aranha mais carente e serntimental, o Tobey foi o Aranha mais experiente e menos assustado com tudo e o Tom foi o mais líder deles tornando o trio de Aranhas perfeito, a nostalgia de ver os antigos vilões em ação dnv foi incrivel dando destaque pro Doutor Octopus que ficou do lado dos mocinhos, a Dupla personalidade do Duende Verde foi incrivel tmb, ver que ele nao é do "mal" quando esta de Norman foi incrível demais, quando ele é possuído pela personalidade do duende verde ele se torna o maior pesadelo dos aranhas, o electro engraçado quando deve ser e sendo vilão quando deve ser, o Lagarto com aquela voz de vilão que não desistiu dos seus objetivos, o homem areia que deixou de confiar nos aranhas depois que descobriu que o Peter não era o "Dele" foi INCRIVEL, emfim... poderia escrever um livro só falando os pontos positivos do filme, vão assistir, é uma experiencia unica, unica mesmo, ver a galera vibrando junto a cada cena não tem explicação, é um filme de ação, aventura, drama e ficção cientifica, você chora quando tem que chorar, da risada quando tem que dar, vibra quando tem que vibrar e etc... é tudo muto bem dosado e no tempo certo, não tem excesso das coisas, vereditos finais... 100% DE APROVAÇÃO EM TODOS OS ASPECTOS, FILMAÇO!!', 1, 7);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Projeto Adam é um filme de 2022 que quer resgatar a nostalgia oitentista. Isso quer dizer que é ruim? Não. É um filme clichê e bom de assistir. A aventura é bem construída e interessante, nos empolgando e sustentando bem toda a história até o final. Algumas coisas são bem inteligentes e foram criativas, principalmente no final. A história fala sobre o amor familiar e a importância de se preocupar com o que queremos. Ryan Reynolds não consegue escapar de Deadpool, mas entrega algumas cenas emocionantes. O seu eu pequeno, só melhora quando deixa de tentar ser um mini Deadpool, mas também entrega uma boa atuação. Ruffalo e Garner só nos fazem lembrar do De Repente 30 e senti falta porque não dançaram Thriller do Michael Jackson. No total o filme é interessante, é uma boa sessão da tarde e vale a pena o dinheiro que investiram. Melhor inclusive do que a produção anterior que tem Reynolds e Netflix, Alerta Vermelho. Quer mais crítica? Siga o @loucosporfilmes no instagram.', 2, 8);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Filme Incrível!!! Foram 1 hora e 42 minutos bem aproveitados pelos roteiristas e diretor, não foram gastadas em cenas sem necessidade, bem ao contrário. O efeito de câmera deu um toque maravilhoso na experiência, juntamente com as cenas que foram gravadas como se estivessem realmente nos anos 70 e o cuidado que tiveram com as máscaras usadas pelo sequestrador. Ele consegue te deixar tenso, com o coração e a curiosidade a mil e ainda dar alguns sustos, mas sem ter que abusar tanto do recurso do terror e no final tudo se encaixou perfeitamente como um quebra-cabeça sem peças a mais nem a menos! O filme me prendeu do início ao fim e confesso que já irei reassistir pela quarta vez. Uma obra fantástica!', 1, 9);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Bem interessante a mensagem do filme. Mostra as faces do mal e como este é capaz de se disfarçar de bom para enganar aqueles que não enxergam de uma forma mais profunda. Fica claro que existe o bem e o mal e um combate entre eles e uma escolha que cada um tem que fazer. E esse lado negro tende a se infiltrar em todos os meios e nas religiões não seria diferente. Não está desfazendo da religião, apenas mostrando que existem os dois lados se combatendo. E as pessoas tem o livre árbitro para escolher e essa escolha tem as suas consequências mais cedo ou mais tarde.', 2, 10);
